config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'series#index'
  resources :series
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
  has_and_belongs_to_many :series
  validates_presence_of :user_name, :rating, :review
end

app/models/series.rb
# frozen_string_literal: true

class Series < ApplicationRecord
  has_and_belongs_to_many :reviews
  validates_presence_of :name, :genre, :seasons_count, :first_release_date, :director, :actor, :shoot_location, :country

  def self.search(term)
    if term.blank?
      all
    else
      where('actor LIKE ?', "%#{term}%")
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/series_controller.rb
# frozen_string_literal: true

class SeriesController < ApplicationController
  def index
    @series = Series.search(series_params[:term])
  end

  private

  def series_params
    params.permit(:term)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/series_helper.rb
# frozen_string_literal: true

module SeriesHelper
  def calculate_average_rating(series)
    series.reviews.average(:rating).to_i
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TvReviews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/series/index.html.erb
<div class="container">
    <%= form_tag(series_index_path, method: :get) do %>
        <div class="row">
            <div class="input-group mt-4 mb-3 col-8">
                <%= search_field_tag :term, nil, class: "form-control", placeholder: "Search by actor"  %>
            </div>
            <%= submit_tag "Search", class: "btn btn-primary col-2 mt-4 mb-3" %>
        </div>
    <% end %>
    
    
    <table class="table table-dark" >
        <thead>
            <tr>
            <th scope="col">TV SERIES</th>
            <th scope="col">ACTOR</th>
            <th scope="col">AVERAGE RATING</th>
            </tr>
        </thead>
        <tbody>
            <% @series.each do |series|%>
                <tr>
                <td><%=series.name%></td>
                <td><%=series.actor%></td>
                <td><%=calculate_average_rating(series) %></td>
                </tr>
            <%end%>
        </tbody>
    </table>
</div>